### ISSUE TITLE
VirusTotal says you have malware 

### ISSUE THREAD

**Issue by superpoussin22** [android-hacker/VirtualXposed#10]
https://www.virustotal.com/fr/file/46f2498311c98dbb890f0642e864c703ca21b6fb8f04f8531ac8d2ea9e601e2e/analysis/1520829060/

**Comment by tiann** [comment]
Thank you, let me take a look

**Comment by tiann** [comment]
It inherit from VirtualApp https://github.com/asLody/VirtualApp/issues/460, I will try to fix it.

**Comment by tiann** [comment]
well, i fixed it partially;

Because the code has some hardcode string such as "base-1.apk", "base.odex"; i simply use base64 to encode these thrings and it was resolved.

**Comment by mirh** [comment]
[You are improving](https://www.virustotal.com/#/file/3ea47e36b16018447721bbaa584b15a0abf15312c87517e75a014fd07838b51a/detection)
Now you are seemingly mostly flagged as "AdLock" or "Agent-QBQ" (whatever they may be)

**Comment by tiann** [comment]
I have fixed the misjudge of all anti-virus engine in newly release (0.8.7)

Here is the test result: https://www.virustotal.com/#/file/3a0540bbc412ea865514a911d98e68f40945ed30284e4ccc441d0754e21568b2/detection

What did i do? These are some commits:

- [Use base64 to encode sensitive strings(openDexFile)](https://github.com/android-hacker/VirtualXposed/commit/d8356e9bb1ac2c4dfeedb3fc531e83fb4e549a59)
- [Call System.setProperty by reflection, avoiding directly call](https://github.com/android-hacker/VirtualXposed/commit/d8356e9bb1ac2c4dfeedb3fc531e83fb4e549a59)
- [Modify the way of print log](https://github.com/android-hacker/VirtualXposed/commit/d8356e9bb1ac2c4dfeedb3fc531e83fb4e549a59) (Are you kidding me?? This can be judged as virus???)
- [Change the class name, from StubContentProvider to StubCP](https://github.com/android-hacker/VirtualXposed/commit/83b12aebed08beb94af6b134638764badbd1ad61) (It is really metaphysics, but it really works.)
- [Rename class, modify log](https://github.com/android-hacker/VirtualXposed/commit/83b12aebed08beb94af6b134638764badbd1ad61)

As you can see, the code before i modified  is surely safe and can not be virus, but it just was misjudged. And the way i fixed the issue is like a metaphyscis, I really do not known why i just print some log and it was judged to virus. Just like a joking.

Anyway, the anti-virus engine is so stupid, and i won't fix any anti-virus issue anymore.

**Comment by lynn-long** [comment]
yes, virustotal is a joke with apk/ipa

**Comment by ghost** [comment]
Why Flagged As Malware?
Because VXP Purpose :)
Xposed Is Used To Modify System on non root enviroment 

Nowadays a lot of av detect app like this as malware even the sc are clean af lol
